services:
  db:
    container_name: presta-db
    image: "postgres:16-alpine3.21"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - presta-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: presta-db
    networks:
      - presta-network
    ports:
      - "5432:5432"

#  backend:
#    container_name: backend
#    depends_on:
#      - backend-db
#    build:
#      context: ./back/.
#    volumes:
#      - ./data:/app/data
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-db/insta_lite_db
#      - SPRING_DATASOURCE_USERNAME=instaliteadmin
#      - SPRING_DATASOURCE_PASSWORD=instAl1t€.!
#      - RESOURCE_PATH=/app/data
#    networks:
#      - instalite
#    ports:
#      - "8080:8080"


#  frontend:
##    depends_on:
##      - backend
#    build:
#      context: ./presta-client/.
#    networks:
#      - presta-network
#    ports:
#      - "4200:80"

  adminer:
    container_name: presta-adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - presta-network
    depends_on:
      - db

  keycloak:
    container_name: keycloak-presta
    image: quay.io/keycloak/keycloak:26.3.3
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: presta-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: keycloak
    volumes:
      - ./realm-export.json:/opt/keycloak/data/realm-export.json
    command:
      - start-dev
      - --import-realm
    networks:
      - presta-network
    depends_on:
      - db



networks:
  presta-network:
    driver: bridge

volumes:
  presta-db-data: