spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/presta-realm"
  application:
    name: presta

  datasource:
    url: jdbc:postgresql://localhost:5432/presta-db
    username: admin
    password: admin
    name: presta-db

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # profiles:
  #   active: dev

springdoc:
  swagger-ui:
    path: /

flyway:
  schemas: presta
  default-schema: presta
  baseline-on-migrate: true

#logging:
#  file:
#    name: logs/presta.log          # écrit aussi dans un fichier (en plus de la console)
#  level:
#    root: INFO
#    # Spring web & MVC
#    org.springframework.web: DEBUG
#    # Spring Security (dont Resource Server)
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.security.oauth2.server.resource: DEBUG
#    # Auto-config report utile en debug
#    org.springframework.boot.autoconfigure: INFO
#    # JPA/Hibernate : SQL + bindings (Hibernate 6+)
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    # Pour Hibernate 5.x (si jamais) : décommente la ligne suivante
#    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    # Flyway
#    org.flywaydb: DEBUG
